org: estagiario
app: serverless-estagiario
service: serverless-estagiario

useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs20.x
  logs:
    restApi: false
  environment:
    ACCESS_TOKEN: ${env:ACCESS_TOKEN}
    OPENAI_KEY: ${env:OPENAI_KEY}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
      - http:
          method: POST
          path: webhook
      - http:
          method: GET
          path: webhook

package:
  exclude:
    - tests/**
    - docs/**
    - .git/**
    - .vscode/**
    - node_modules/@types/**
    - node_modules/@aws-sdk/**
    - node_modules/serverless-offline/**
    - node_modules/serverless-offline/**
    - node_modules/serverless-plugin-optimize/**
    - node_modules/@nestjs/cli
    - node_modules/@nestjs/schematics
    - node_modules/@nestjs/testing
    - node_modules/@typescript-eslint/eslint-plugin
    - node_modules/@typescript-eslint/parser
    - node_modules/eslint
    - node_modules/eslint-config-prettier
    - node_modules/eslint-plugin-prettier
    - node_modules/jest
    - node_modules/plugin
    - node_modules/prettier
    - node_modules/prisma
    - node_modules/serverless-offline
    - node_modules/serverless-plugin-optimize
    - node_modules/serverless-plugin-typescript
    - node_modules/source-map-support
    - node_modules/supertest
    - node_modules/ts-jest
    - node_modules/ts-loader
    - node_modules/ts-node
    - node_modules/tsconfig-paths
    - node_modules/typescript
