org: estagiario
app: serverless-estagiario
service: serverless-estagiario

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  logs:
    restApi: false
  environment:
    ACCESS_TOKEN: ${env:ACCESS_TOKEN}
    OPENAI_KEY: ${env:OPENAI_KEY}
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
      - http:
          method: POST
          path: webhook
      - http:
          method: GET
          path: webhook

package:
  exclude:
    - tests/**
    - docs/**
    - .git/**
    - .vscode/**
    - node_modules/aws-sdk/**
